### ISSUE TITLE
Convert -99;-98;-97;-96 into NaNs from the SCORE dataset

### ISSUE THREAD

**Issue by AidaasinAyda** [brickstudymasons/brickstudy#42]

**Comment by drcandacemakedamoore** [comment]
Done in final table, but turned out to be currently irrrelevant (-9Xs were dropped earlier, must be discussed)

**Comment by drcandacemakedamoore** [comment]
Done in final table, but turned out to be currently irrrelevant (-9Xs were dropped earlier, must be discussed)

**Comment by drcandacemakedamoore** [comment]
Done in final table, but turned out to be currently irrelevant (-9Xs were dropped earlier, must be discussed)
